//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_Pro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalog_note
    {
        public int Id_Cont { get; set; }
        public string Nume_Materie { get; set; }
        public Nullable<int> Nota_Examen { get; set; }
        public string Data_Examen { get; set; }
        public Nullable<int> Nota_restanta { get; set; }
        public string Data_restanta { get; set; }
        public Nullable<int> Nr_credite { get; set; }
        public int Id_nota { get; set; }
    
        public virtual Studenti Studenti { get; set; }
    }
}
