//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_Pro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conturi
    {
        public int Id_Cont { get; set; }
        public string User_nameX { get; set; }
        public string PasswordX { get; set; }
        public Nullable<int> Nivel_acces { get; set; }
    
        public virtual myimage myimage { get; set; }
        public virtual Profesori Profesori { get; set; }
        public virtual Studenti Studenti { get; set; }
    }
}
