//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_Pro
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FacultateaXEntities1 : DbContext
    {
        public FacultateaXEntities1()
            : base("name=FacultateaXEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Catalog_note> Catalog_note { get; set; }
        public virtual DbSet<Conturi> Conturis { get; set; }
        public virtual DbSet<Grupe> Grupes { get; set; }
        public virtual DbSet<Materii> Materiis { get; set; }
        public virtual DbSet<myimage> myimages { get; set; }
        public virtual DbSet<Profesori> Profesoris { get; set; }
        public virtual DbSet<Studenti> Studentis { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
