//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_Pro
{
    using System;
    using System.Collections.Generic;
    
    public partial class myimage
    {
        public int Id_cont { get; set; }
        public byte[] img { get; set; }
    
        public virtual Conturi Conturi { get; set; }
    }
}
