//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_Pro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profesori
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Profesori()
        {
            this.Grupes = new HashSet<Grupe>();
            this.Materiis = new HashSet<Materii>();
        }
    
        public int Id_Cont { get; set; }
        public string Nume { get; set; }
        public string Prenume { get; set; }
        public string Numar_telefon { get; set; }
        public string Email { get; set; }
        public string Adresa { get; set; }
        public string Functie { get; set; }
    
        public virtual Conturi Conturi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Grupe> Grupes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Materii> Materiis { get; set; }
    }
}
