//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_Pro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Studenti
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Studenti()
        {
            this.Catalog_note = new HashSet<Catalog_note>();
        }
    
        public int Id_Cont { get; set; }
        public string Nume { get; set; }
        public Nullable<int> Id_Grupa { get; set; }
        public Nullable<int> An_Studiu { get; set; }
        public string Specializare { get; set; }
        public string Forma_invatamant { get; set; }
        public Nullable<int> Numar_restante { get; set; }
        public string Prenume { get; set; }
        public string Numar_telefon { get; set; }
        public string Email { get; set; }
        public string Adresa { get; set; }
        public string CNP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Catalog_note> Catalog_note { get; set; }
        public virtual Conturi Conturi { get; set; }
        public virtual Grupe Grupe { get; set; }
    }
}
